TYPE=TRIGGERS
triggers='CREATE DEFINER=`root`@`%` trigger functions_insert after insert on functions\nfor each row\ninsert into changelog (object,objectid,operation,clock)\nvalues (7,new.functionid,1,unix_timestamp())' 'CREATE DEFINER=`root`@`%` trigger functions_update after update on functions\nfor each row\ninsert into changelog (object,objectid,operation,clock)\nvalues (7,old.functionid,2,unix_timestamp())' 'CREATE DEFINER=`root`@`%` trigger functions_delete before delete on functions\nfor each row\ninsert into changelog (object,objectid,operation,clock)\nvalues (7,old.functionid,3,unix_timestamp())'
sql_modes=1411383296 1411383296 1411383296
definers='root@%' 'root@%' 'root@%'
client_cs_names='utf8mb4' 'utf8mb4' 'utf8mb4'
connection_cl_names='utf8mb4_bin' 'utf8mb4_bin' 'utf8mb4_bin'
db_cl_names='utf8mb4_bin' 'utf8mb4_bin' 'utf8mb4_bin'
created=1719393236127936 1719393236130739 1719393236133875
